# eksctl create cluster -f ./eks-cluster.yaml
# eks-cluster.yaml
---
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: k8ssec101
  region: us-east-1

managedNodeGroups:
  - name: managed-ng-1
    instanceType: t2.small
    minSize: 1
    maxSize: 3
    desiredCapacity: 1
    volumeSize: 8
    labels: {role: worker}
    tags:
      nodegroup-role: worker
